# -*- coding: utf-8 -*-
"""Semester Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BTRUT3ajYtdKyNHLFq9asCT8Rio6ax-j
"""

import numpy as np
import pandas as pd
import yfinance as yf
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

# Function to fetch historical stock data from Yahoo Finance
def get_stock_data(symbol, start_date, end_date):
    stock_data = yf.download(symbol, start=start_date, end=end_date)
    return stock_data

# Function to preprocess data and create input features and labels for LSTM
def prepare_data(data, window_size):
    data_scaled = scaler.fit_transform(data.values.reshape(-1, 1))

    X, y = [], []
    for i in range(len(data_scaled) - window_size):
        X.append(data_scaled[i:(i + window_size), 0])
        y.append(data_scaled[i + window_size, 0])

    X, y = np.array(X), np.array(y)
    return X, y

# Define LSTM model
def create_lstm_model(input_shape):
    model = Sequential()
    model.add(LSTM(units=50, return_sequences=True, input_shape=input_shape))
    model.add(LSTM(units=50, return_sequences=False))
    model.add(Dense(units=1))
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

stock_symbol = 'UBER'
start_date = '2020-01-01'
end_date = '2024-07-01'
window_size = 20

# Fetch stock data
stock_data = get_stock_data(stock_symbol, start_date, end_date)
print(stock_data)

# Select the 'Close' price for prediction
data_to_use = stock_data[['Close', 'Open']]

# Normalize the data using Min-Max scaling
scaler = MinMaxScaler(feature_range=(0, 1))
data_scaled = scaler.fit_transform(data_to_use.values.reshape(-1, 1))

# Prepare data for LSTM
X, y = prepare_data(data_to_use, window_size)

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

# Reshape input for LSTM (samples, time steps, features)
X_train = X_train.reshape(X_train.shape[0], X_train.shape[1], 1)
X_test = X_test.reshape(X_test.shape[0], X_test.shape[1], 1)
# Create LSTM model
model = create_lstm_model((X_train.shape[1], 1))

# Train the model
model.fit(X_train, y_train, epochs=50, batch_size=32)

# Make predictions on the test set
predictions = model.predict(X_test)

# Inverse transform the predictions and actual values
predictions = scaler.inverse_transform(predictions)
y_test = scaler.inverse_transform(y_test.reshape(-1, 1))

# Calculate Mean Squared Error
mse = mean_squared_error(y_test, predictions)
print(f'Mean Squared Error: {mse}')

# Visualize the predictions
import matplotlib.pyplot as plt
plt.figure(figsize=(15, 6))
plt.plot(stock_data.index[-len(predictions):], predictions, label='Predicted')
plt.plot(stock_data.index[-len(y_test):], y_test, label='Actual')
plt.title(f'Stock Price Prediction for {stock_symbol}')
plt.xlabel('Date')
plt.ylabel('Stock Price')
plt.legend()
plt.show()
