# -*- coding: utf-8 -*-
"""streamlit_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d3Qz6BEq_4f8MqN0mMOLOY3RN3D7K6Qb
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib

def identity_transform(x):
    return x

# Load pipeline
pipeline = joblib.load("churn_pipeline.pkl")

# App title
st.title("📉 Customer Churn Predictor")
st.markdown("Fill in the customer details to predict their churn risk.")

# Binary map
yes_no_map = {"No": 0, "Yes": 1}

# Input fields
gender = st.selectbox("Gender", ["Male", "Female"])
senior = st.selectbox("Senior Citizen", ["No", "Yes"])
partner = st.selectbox("Has Partner?", ["No", "Yes"])
dependents = st.selectbox("Has Dependents?", ["No", "Yes"])
tenure = st.slider("Tenure (months)", 0, 72, 12)
phone_service = st.selectbox("Phone Service", ["No", "Yes"])
multiple_lines = st.selectbox("Multiple Phone Lines", ["No", "Yes"])
internet_service = st.selectbox("Internet Service", ["No", "DSL", "Fiber optic"])
online_security = st.selectbox("Online Security", ["No", "Yes"])
online_backup = st.selectbox("Online Backup", ["No", "Yes"])
device_protection = st.selectbox("Device Protection", ["No", "Yes"])
tech_support = st.selectbox("Tech Support", ["No", "Yes"])
streaming_tv = st.selectbox("Streaming TV", ["No", "Yes"])
streaming_movies = st.selectbox("Streaming Movies", ["No", "Yes"])
contract = st.selectbox("Contract Type", ["Month-to-month", "One year", "Two year"])
paperless_billing = st.selectbox("Paperless Billing", ["No", "Yes"])
payment_method = st.selectbox("Payment Method", ["Electronic check", "Mailed check", "Bank transfer", "Credit card"])
monthly_charges = st.number_input("Monthly Charges", 0.0, 200.0, 70.0)
total_charges = st.number_input("Total Charges", 0.0, 10000.0, 2500.0)

# Feature mapping for encoding
gender_map = {"Female": 0, "Male": 1}
internet_service_map = {"No": 0, "DSL": 1, "Fiber optic": 2}
contract_map = {"Month-to-month": 0, "One year": 1, "Two year": 2}
payment_map = {
    "Electronic check": 0,
    "Mailed check": 1,
    "Bank transfer": 2,
    "Credit card": 3
}

# Create input DataFrame
input_data = pd.DataFrame([[
    gender_map[gender],
    yes_no_map[senior],
    yes_no_map[partner],
    yes_no_map[dependents],
    tenure,
    yes_no_map[phone_service],
    yes_no_map[multiple_lines],
    internet_service_map[internet_service],
    yes_no_map[online_security],
    yes_no_map[online_backup],
    yes_no_map[device_protection],
    yes_no_map[tech_support],
    yes_no_map[streaming_tv],
    yes_no_map[streaming_movies],
    contract_map[contract],
    yes_no_map[paperless_billing],
    payment_map[payment_method],
    monthly_charges,
    total_charges
]], columns=[
    "gender", "SeniorCitizen", "Partner", "Dependents", "tenure", "PhoneService",
    "MultipleLines", "InternetService", "OnlineSecurity", "OnlineBackup", "DeviceProtection",
    "TechSupport", "StreamingTV", "StreamingMovies", "Contract",
    "PaperlessBilling", "PaymentMethod", "MonthlyCharges", "TotalCharges"
])

# Predict
if st.button("Predict Churn"):
    prediction = pipeline.predict(input_data)[0]
    prob = pipeline.predict_proba(input_data)[0][1]
    st.write(f"**Prediction:** {'Churn' if prediction == 1 else 'No Churn'}")
    st.write(f"**Churn Probability:** {prob:.2%}")