# -*- coding: utf-8 -*-
"""MiniGoogleTranslator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16JlQ4OrVlfZ_PG1Oy-ASh4YOYDmxY0-j
"""

import pandas as pd


# Containers for parsed data
english_sentences = []
telugu_sentences = []

with open("english_telugu_data.txt", "r", encoding="utf-8") as f:
    for line in f:
        if "++++$++++" not in line:
            continue  # Skip malformed lines
        english, telugu = line.strip().split("++++$++++")
        english_sentences.append(english.strip())
        telugu_sentences.append(telugu.strip())

# Step 2: Create a DataFrame
df = pd.DataFrame({"English": english_sentences, "Telugu": telugu_sentences})

# Step 3: Clean any leftover formatting like '++++$++++'
df["English"] = df["English"].str.replace("++++$++++", "", regex=False).str.strip()
df["Telugu"] = df["Telugu"].str.replace("++++$++++", "", regex=False).str.strip()

# Optional: drop too-short rows or blanks
df = df[df["English"].str.len() > 1]
df = df[df["Telugu"].str.len() > 1]

# Step 4: Check result
print(f"✅ Cleaned dataset: {len(df)} sentence pairs")
print(df.sample(5))

# Step 5: Save to clean CSV file
df.to_csv("cleaned_en_te_final.csv", index=False)

!pip install transformers datasets sentencepiece sacrebleu

from datasets import Dataset

# Load your cleaned dataset
df = pd.read_csv("cleaned_en_te_final.csv")

# Rename columns to match expected format
df = df.rename(columns={"English": "translation_en", "Telugu": "translation_te"})

# Hugging Face wants 'translation': {'en': ..., 'te': ...}
df["translation"] = df.apply(lambda x: {"en": x["translation_en"], "te": x["translation_te"]}, axis=1)

# Convert to HF Dataset
hf_dataset = Dataset.from_pandas(df[["translation"]])
hf_dataset = hf_dataset.train_test_split(test_size=0.1)

from transformers import MarianTokenizer, MarianMTModel

model_name = "Helsinki-NLP/opus-mt-en-dra"
tokenizer = MarianTokenizer.from_pretrained(model_name)
model = MarianMTModel.from_pretrained(model_name)

# Prepend the language token for Telugu
src_text = ">>te<< This is a book."
inputs = tokenizer(src_text, return_tensors="pt", padding=True, truncation=True)
outputs = model.generate(**inputs)
translated = tokenizer.decode(outputs[0], skip_special_tokens=True)
print(translated)

def preprocess_function(examples):
    # Extract lists of English and Telugu sentences
    inputs = [ex["en"] for ex in examples["translation"]]
    targets = [ex["te"] for ex in examples["translation"]]

    # Tokenize inputs and targets
    model_inputs = tokenizer(
        inputs, max_length=128, truncation=True, padding="max_length"
    )

    with tokenizer.as_target_tokenizer():
        labels = tokenizer(
            targets, max_length=128, truncation=True, padding="max_length"
        )

    model_inputs["labels"] = labels["input_ids"]
    return model_inputs
tokenized_ds = hf_dataset.map(preprocess_function, batched=True)

from transformers import Seq2SeqTrainer, Seq2SeqTrainingArguments, DataCollatorForSeq2Seq
import os

# Disable Weights & Biases logging (optional)
os.environ["WANDB_DISABLED"] = "true"

training_args = Seq2SeqTrainingArguments(
    output_dir="./results-en-te",
    do_train=True,
    do_eval=True,
    learning_rate=5e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    weight_decay=0.01,
    save_total_limit=2,
    num_train_epochs=3,
    predict_with_generate=True,
    logging_dir="./logs",
    logging_steps=50,
    save_steps=500,
    eval_steps=500,
    logging_first_step=True,
    fp16=False
)

data_collator = DataCollatorForSeq2Seq(tokenizer, model=model)

trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_ds["train"],
    eval_dataset=tokenized_ds["test"],
    tokenizer=tokenizer,
    data_collator=data_collator
)

# STEP 5: Train the Model
trainer.train()

def translate(text):
    inputs = tokenizer(text, return_tensors="pt", padding=True, truncation=True)
    outputs = model.generate(**inputs)
    return tokenizer.decode(outputs[0], skip_special_tokens=True)

# Try a few test translations
print(translate("What is your name?"))
print(translate("I am learning machine translation."))

model.save_pretrained("en_te_translator_model")
tokenizer.save_pretrained("en_te_translator_model")

from transformers import MarianTokenizer, MarianMTModel

# Replace with your actual model path (local or Hugging Face repo if pushed)
model_path = "./en_te_translator_model"
tokenizer = MarianTokenizer.from_pretrained(model_path)
model = MarianMTModel.from_pretrained(model_path)

tokenizer.src_lang = "en"

# Sample sentences to translate
sentences = [
    "What is your name?",
    "How are you?",
    "I am learning machine translation.",
    "This is a book.",
    "My name is Atresh Tata. Born in Warangal.",
    "She likes mangoes.",
    "We are going to school.",
    "I don't know."
]

for sentence in sentences:
    inputs = tokenizer(sentence, return_tensors="pt", padding=True, truncation=True)
    outputs = model.generate(**inputs)
    translated = tokenizer.decode(outputs[0], skip_special_tokens=True)
    print(f"❯ {sentence} ➝ {translated}")